version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0
    working_directory: ~/repo

jobs:
  install_and_build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build the Project
          command: npm run build
#      - run:
#          name: Export Static Files
#          command: npm run export
#      - persist_to_workspace:
#          root: ~/repo/out
#          paths:
#            - .

  deploy_vercel:
    executor: node-executor
    steps:
#      - attach_workspace:
#          at: ~/repo/out
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel --prod --token $VERCEL_TOKEN --yes --scope $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_and_build
      - deploy_vercel:
          requires:
            - install_and_build
